### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 

### ISSUE THREAD

**Issue by arthurlogilab** [landscapeio/dodgy#15]
```
$ dodgy ---help                                                         │
Traceback (most recent call last):
  File "/usr/bin/dodgy", line 4, in <module>
    dodgy.run.run()
  File "/usr/lib/python3/dist-packages/dodgy/run.py", line 56, in run
    warnings = run_checks(os.getcwd())
  File "/usr/lib/python3/dist-packages/dodgy/run.py", line 44, in run_checks
    for msg_parts in check_file(filepath):
  File "/usr/lib/python3/dist-packages/dodgy/checks.py", line 72, in check_file
    return check_file_contents(to_check.read())
  File "/usr/lib/python3.6/codecs.py", line 700, in read
    return self.reader.read(size)
  File "/usr/lib/python3.6/codecs.py", line 503, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 787: invalid continuation byte
$ dpkg -l dodgy                                                         │
ii  dodgy                   0.1.9-3          all              searches for dodgy looking lines in Python code
```

**Comment by Lightslayer** [comment]
I got the same issue after doing a `pip install dodgy` on Ubuntu 18.04 - unfortunately I'm not sure how to begin to fix :-(
